AUTHOR_USERNAME = 'TestAuthor'
USER_USERNAME = 'test_user'
GROUP_TITLE = 'Тестовая группа'
GROUP_SLUG = 'test-slug'
GROUP_DESCRIPTION = 'Тестовое описание'
POST_TEXT = 'Тестовый пост проверка'
POST_EDIT_TEXT = 'Изменяем пост'
COMMENT_TEXT = 'Тестовый комментарий'

INDEX_URL_NAME = 'posts:index'
GROUP_LIST_URL_NAME = 'posts:group_list'
PROFILE_URL_NAME = 'posts:profile'
POST_DETAIL_URL_NAME = 'posts:post_detail'
POST_EDIT_URL_NAME = 'posts:post_edit'
POST_CREATE_URL_NAME = 'posts:post_create'
POST_DETAIL_COMMENT_URL_NAME = 'posts:add_comment'
POST_FOLLOW_URL_NAME = 'posts:follow_index'

INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
POST_EDIT_TEMPLATE = 'posts/create_post.html'
POST_CREATE_TEMPLATE = 'posts/create_post.html'
HTTP404_HTML_TEMPLATE = 'core/404.html'
